# fly.toml app configuration file generated for old-mountain-7070 on 2023-06-08T17:02:37-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "old-mountain-7070"
primary_region = "bos"

[[services]]
internal_port = 7878
protocol = "tcp"

[services.concurrency]
hard_limit = 150

[[services.ports]]
port = 7878

[[services]]
internal_port = 7878
protocol = "udp"

[[services.ports]]
port = 7878

[env]
UDP_ADDRESS = "fly-global-services"

[deploy]
strategy = "immediate"
